pipeline {
    agent any
    parameters {
        string(
            name: 'BRANCH_NAME',
            defaultValue: 'develop',
            description: 'Git branch to build'
        )
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World from Jenkins 🚀'
            }
        }
        stage('complete') {
            steps {
                echo 'Complete build'
            }
        }
    }
}