pipeline {
    agent any
    parameters {
        string(
            name: 'BRANCH_NAME',
            defaultValue: 'develop',
            description: 'Git branch to build'
        )
        string(
            name: 'IMAGE_TAG',
            defaultValue: '0.0.1',
            description: 'Image tag to build'
        )
    }

    environment {
        IMAGE_NAME = "node-demo-app-jenkin"
        CONTAINER_NAME = "node-demo-jenkin-container"
        APP_PORT = "3000"
    }

    stages {
        stage('Hello') {
            steps {
                echo "SCM = ${scm.userRemoteConfigs}"
                echo "Building branch: ${params.BRANCH_NAME}"
                echo "Image tag: ${params.IMAGE_TAG}"
                echo 'Hello World from Jenkins 🚀'
            }
        }
        stage('Checkout') {
            steps {
                script {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: "*/${params.BRANCH_NAME}"]],
                        userRemoteConfigs: scm.userRemoteConfigs
                    ])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $IMAGE_NAME:${IMAGE_TAG} .
                '''
            }
        }

        stage('complete') {
            steps {
                echo 'Complete build'
            }
        }
    }
}